version: '3.8'
services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    ports:
      - "5432:5432"
    volumes:
      - "D:\\service\\db_postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD={password} #if it doesn't work, you can try to change the password by sql
      - POSTGRES_DB=recruitment_dev
    networks:
      - db

  redis:
    image: redis:latest
    restart: always
    container_name: db_redis
    ports:
      - "6379:6379"
    volumes:
      - D:\\service\\db_redis:/data
    command: [ "redis-server", "--requirepass", "your_password" ]
    expose:
      - "6379:6379"
    networks:
      - db

  recruitment_backend2023:
    build: .
    container_name: project_recruitment_backend
    ports:
      - "54251:54251"
    volumes:
      - "./data/logs:/app/data/logs" #日志
      - "./data/resumes:/app/data/resumes" #简历
    networks:
      - db

networks:
  db:
    external: true
    name: db
